  const ADVANTAGE_EMPLOYEE_OFFERS_TYPE_OF_PRODUCTS = [
    { value: "Credit Card", label: "Credit Card" },
    { value: "HL", label: "Housing loan" },
    { value: "Health Insurance", label: "Health Insurance" },
    { value: "Stocks & Securities", label: "Demat Account" },
    { value: "Salary Term", label: "Life Insurance - Super Term Plan" },
    { value: "Mutual Fund", label: "Mutual Fund" },
    { value: "PL", label: "Personal Loan" },
    { value: "NPS Vatsalya", label: "NPS Vatsalya" },
    { value: "HE Top up", label: "Health Insurance - Super Top Up" },
    { value: "Forex", label: "Forex" },
    { value: "Corporate NPS", label: "Corporate NPS" },
    { value: "Life Insurance", label: "Life Insurance - Saving Plan - Nishchit Aayush" },
    { value: "Gold Loan", label: "Gold Loan" },
    { value: "LAMF", label: "Loan Against Mutual Fund" },
    { value: "car", label: "Motor Insurance - Tata AIG" },
  ];

const ADVANTAGE_EMPLOYEE_OFFERS_COMPANY_OPTIONS = [
  { label: "ABNL Investment Ltd", value: "ABNL Investment Ltd" },
  { label: "ABReL (MP) Renewables EPC Ltd", value: "ABReL (MP) Renewables EPC Ltd" },
  { label: "ABReL (Odisha) SPV Ltd.", value: "ABReL (Odisha) SPV Ltd." },
  { label: "ABReL (RJ) Projects Ltd", value: "ABReL (RJ) Projects Ltd" },
  { label: "ABReL Century Energy Ltd", value: "ABReL Century Energy Ltd" },
  { label: "ABReL Green Energy Ltd.", value: "ABReL Green Energy Ltd." },
  { label: "ABReL Hybrid Projects Ltd", value: "ABReL Hybrid Projects Ltd" },
  { label: "ABReL Renewables EPC Ltd.", value: "ABReL Renewables EPC Ltd." },
  { label: "ABReL Solar Power Ltd.", value: "ABReL Solar Power Ltd." },
  { label: "ABReL SPV 2 Ltd", value: "ABReL SPV 2 Ltd" },
  { label: "Aditya Birla ARC Ltd", value: "Aditya Birla ARC Ltd" },
  { label: "Aditya Birla Capital Digital Ltd", value: "Aditya Birla Capital Digital Ltd" },
  { label: "Aditya Birla Capital Ltd", value: "Aditya Birla Capital Ltd" },
  { label: "Aditya Birla Capital Technology Services Ltd", value: "Aditya Birla Capital Technology Services Ltd" },
  { label: "Aditya Birla Fashion and Retail Ltd (ABFRL)", value: "Aditya Birla Fashion and Retail Ltd (ABFRL)" },
  { label: "House of Masaba Lifestyle Pvt Ltd (ABFRL)", value: "House of Masaba Lifestyle Pvt Ltd (ABFRL)" },
  { label: "Indivinity Clothing Retail Pvt Ltd (ABFRL)", value: "Indivinity Clothing Retail Pvt Ltd (ABFRL)" },
  { label: "Jaypore E Commerce Pvt Ltd (ABFRL)", value: "Jaypore E Commerce Pvt Ltd (ABFRL)" },
  { label: "Sabyasachi Calcutta LLP (ABFRL)", value: "Sabyasachi Calcutta LLP (ABFRL)" },
  { label: "Styleverse Lifestyle Pvt Ltd (ABFRL)", value: "Styleverse Lifestyle Pvt Ltd (ABFRL)" },
  { label: "TCNS Clothing Co. Ltd (ABFRL)", value: "TCNS Clothing Co. Ltd (ABFRL)" },
  { label: "TMRW - House of Brands (ABFRL)", value: "TMRW - House of Brands (ABFRL)" },
  { label: "Pantaloons (ABFRL)", value: "Pantaloons (ABFRL)" },
  { label: "Aditya Birla Finance Ltd", value: "Aditya Birla Finance Ltd" },
  { label: "Aditya Birla Financial Shared Services Ltd", value: "Aditya Birla Financial Shared Services Ltd" },
  { label: "Aditya Birla Garments Ltd", value: "Aditya Birla Garments Ltd" },
  { label: "Aditya Birla Health Insurance Company", value: "Aditya Birla Health Insurance Company" },
  { label: "Aditya Birla Housing Finance Ltd", value: "Aditya Birla Housing Finance Ltd" },
  { label: "Aditya Birla Insulators", value: "Aditya Birla Insulators" },
  { label: "Aditya Birla Lifestyle Brands Limited (ABLBL)", value: "Aditya Birla Lifestyle Brands Limited (ABLBL)" },
  { label: "Aditya Birla Management Corporation Pvt Ltd", value: "Aditya Birla Management Corporation Pvt Ltd" },
  { label: "Aditya Birla Money Insurance Advisory Services Ltd", value: "Aditya Birla Money Insurance Advisory Services Ltd" },
  { label: "Aditya Birla Money Ltd", value: "Aditya Birla Money Ltd" },
  { label: "Aditya Birla Money Mart Ltd", value: "Aditya Birla Money Mart Ltd" },
  { label: "Aditya Birla New Age Hospitality", value: "Aditya Birla New Age Hospitality" },
  { label: "Aditya Birla PE Advisors Pvt Ltd", value: "Aditya Birla PE Advisors Pvt Ltd" },
  { label: "Aditya Birla Power Composites Ltd", value: "Aditya Birla Power Composites Ltd" },
  { label: "Aditya Birla Real Estates Ltd", value: "Aditya Birla Real Estates Ltd" },
  { label: "Aditya Birla Renewables Energy Ltd", value: "Aditya Birla Renewables Energy Ltd" },
  { label: "Aditya Birla Renewables Green Power Ltd", value: "Aditya Birla Renewables Green Power Ltd" },
  { label: "Aditya Birla Renewables Ltd", value: "Aditya Birla Renewables Ltd" },
  { label: "Aditya Birla Renewables Solar Ltd", value: "Aditya Birla Renewables Solar Ltd" },
  { label: "Aditya Birla Renewables SPV 1 Ltd", value: "Aditya Birla Renewables SPV 1 Ltd" },
  { label: "Aditya Birla Renewables Subsiadiary Ltd", value: "Aditya Birla Renewables Subsiadiary Ltd" },
  { label: "Aditya Birla Renewables Utkal Ltd", value: "Aditya Birla Renewables Utkal Ltd" },
  { label: "Aditya Birla Science and Technology Company Pvt Ltd (ABSTCL)", value: "Aditya Birla Science and Technology Company Pvt Ltd (ABSTCL)" },
  { label: "Aditya Birla Stressed Asset AMC Pvt Ltd", value: "Aditya Birla Stressed Asset AMC Pvt Ltd" },
  { label: "Aditya Birla Sun Life Asset Management Company Ltd", value: "Aditya Birla Sun Life Asset Management Company Ltd" },
  { label: "Aditya Birla Sun Life Insurance Company Ltd (ABSLI)", value: "Aditya Birla Sun Life Insurance Company Ltd (ABSLI)" },
  { label: "Aditya Birla Sun Life Mutual Fund", value: "Aditya Birla Sun Life Mutual Fund" },
  { label: "Aditya Birla Sun Life Pension Management Company Ltd", value: "Aditya Birla Sun Life Pension Management Company Ltd" },
  { label: "Aditya Birla Sun Life Trustee Pvt Ltd", value: "Aditya Birla Sun Life Trustee Pvt Ltd" },
  { label: "Aditya Birla Trustee Company Pvt Ltd", value: "Aditya Birla Trustee Company Pvt Ltd" },
  { label: "Aditya Birla Ventures", value: "Aditya Birla Ventures" },
  { label: "Aditya Birla Wellness Pvt Ltd", value: "Aditya Birla Wellness Pvt Ltd" },
  { label: "Amelia Coal Mining Ltd", value: "Amelia Coal Mining Ltd" },
  { label: "Applause Entertainment", value: "Applause Entertainment" },
  { label: "Avarna Projects LLP", value: "Avarna Projects LLP" },
  { label: "Awesomefab Shopping Pvt Ltd", value: "Awesomefab Shopping Pvt Ltd" },
  { label: "Ayana Renewable Power Four", value: "Ayana Renewable Power Four" },
  { label: "Bewakoof Brands Pvt Ltd", value: "Bewakoof Brands Pvt Ltd" },
  { label: "Bhagwati Limestone Company Pvt Ltd", value: "Bhagwati Limestone Company Pvt Ltd" },
  { label: "Bhaskarpara Coal Company Ltd", value: "Bhaskarpara Coal Company Ltd" },
  { label: "Bhubaneswari Coal Mining Ltd", value: "Bhubaneswari Coal Mining Ltd" },
  { label: "Birla Management Centre Services Limited", value: "Birla Management Centre Services Limited" },
  { label: "Birla Advanced Knits Pvt Ltd", value: "Birla Advanced Knits Pvt Ltd" },
  { label: "Birla Arnaa LLP", value: "Birla Arnaa LLP" },
  { label: "Birla Century Exports Pvt Ltd", value: "Birla Century Exports Pvt Ltd" },
  { label: "Birla Century International LLC", value: "Birla Century International LLC" },
  { label: "Birla Copper Asoj Pvt Ltd", value: "Birla Copper Asoj Pvt Ltd" },
  { label: "Birla Cosmetics", value: "Birla Cosmetics" },
  { label: "Birla Estate", value: "Birla Estate" },
  { label: "Birla Opus", value: "Birla Opus" },
  { label: "Birla Pivot", value: "Birla Pivot" },
  { label: "Birla Tisya LLP", value: "Birla Tisya LLP" },
  { label: "Century Enka", value: "Century Enka" },
  { label: "Century Pulp and Paper", value: "Century Pulp and Paper" },
  { label: "Copper Jana Seva Trust", value: "Copper Jana Seva Trust" },
  { label: "Coromandel Electric Company Ltd", value: "Coromandel Electric Company Ltd" },
  { label: "Coromandel Sugars Ltd", value: "Coromandel Sugars Ltd" },
  { label: "Dahej Harbour & Infrastructure Ltd", value: "Dahej Harbour & Infrastructure Ltd" },
  { label: "East Coast Bauxite Mining Company Pvt Ltd", value: "East Coast Bauxite Mining Company Pvt Ltd" },
  { label: "Essel Mining & Industries Ltd", value: "Essel Mining & Industries Ltd" },
  { label: "Finesse International Design Pvt Ltd", value: "Finesse International Design Pvt Ltd" },
  { label: "Goodview Fashion Pvt Ltd", value: "Goodview Fashion Pvt Ltd" },
  { label: "Gotan Limestone Khanij Udyog Pvt Ltd", value: "Gotan Limestone Khanij Udyog Pvt Ltd" },
  { label: "Grasim Business Services Pvt Ltd", value: "Grasim Business Services Pvt Ltd" },
  { label: "Grasim Industries limited", value: "Grasim Industries limited" },
  { label: "Greenyana Sunstream Pvt Ltd", value: "Greenyana Sunstream Pvt Ltd" },
  { label: "Hindalco Almex Aerospace Ltd (HAAL)", value: "Hindalco Almex Aerospace Ltd (HAAL)" },
  { label: "Hindalco Industries Ltd", value: "Hindalco Industries Ltd" },
  { label: "Hindalco Jana Seva Trust", value: "Hindalco Jana Seva Trust" },
  { label: "Imperial online services Pvt Ltd", value: "Imperial online services Pvt Ltd" },
  { label: "India Cements Ltd", value: "India Cements Ltd" },
  { label: "Jayashree Textiles", value: "Jayashree Textiles" },
  { label: "Letein Valley Cement Ltd", value: "Letein Valley Cement Ltd" },
  { label: "Lucknow Finance Company Ltd", value: "Lucknow Finance Company Ltd" },
  { label: "Madanpur (North) Coal Company Pvt Ltd", value: "Madanpur (North) Coal Company Pvt Ltd" },
  { label: "Mahan Coal Ltd", value: "Mahan Coal Ltd" },
  { label: "Minerals & Minerals Ltd", value: "Minerals & Minerals Ltd" },
  { label: "MNH Shakti Ltd", value: "MNH Shakti Ltd" },
  { label: "Next Tree Products Pvt Ltd", value: "Next Tree Products Pvt Ltd" },
  { label: "Novel Jewels", value: "Novel Jewels" },
  { label: "Pratyaya E-commerce Pvt Ltd", value: "Pratyaya E-commerce Pvt Ltd" },
  { label: "Raasi Gold", value: "Raasi Gold" },
  { label: "ReNew Surya Uday Pvt Ltd", value: "ReNew Surya Uday Pvt Ltd" },
  { label: "Renuka Investments & Finance Limited", value: "Renuka Investments & Finance Limited" },
  { label: "Renukeshwar Investments & Finance Ltd", value: "Renukeshwar Investments & Finance Ltd" },
  { label: "Samruddhi Swastik Trading and Investments Ltd", value: "Samruddhi Swastik Trading and Investments Ltd" },
  { label: "Star Cement", value: "Star Cement" },
  { label: "Suvas Holdings Limited", value: "Suvas Holdings Limited" },
  { label: "TG Apparel & Décor Pvt Ltd", value: "TG Apparel & Décor Pvt Ltd" },
  { label: "Tubed Coal Mines Ltd", value: "Tubed Coal Mines Ltd" },
  { label: "Ultratech Cement", value: "Ultratech Cement" },
  { label: "Utkal Alumina International Ltd", value: "Utkal Alumina International Ltd" },
  { label: "Utkal Alumina Jan Seva Trust", value: "Utkal Alumina Jan Seva Trust" },
  { label: "Vodafone Idea", value: "Vodafone Idea" }
];


  export { ADVANTAGE_EMPLOYEE_OFFERS_TYPE_OF_PRODUCTS, ADVANTAGE_EMPLOYEE_OFFERS_COMPANY_OPTIONS };